os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.11.1"
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - $HOME/.m2
    - $HOME/.yarn-cache
env:
  global:
    - NODE_VERSION=6.11.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - wget -qO- https://get.docker.com/ | sh
  - docker version
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
script:
  - chmod +x mvnw
  - docker-compose -f src/main/docker/postgresql.yml up -d
  - docker-compose -f src/main/docker/elasticsearch.yml up -d
  - ./mvnw clean test
  - yarn test
  - ./mvnw package -Pprod -DskipTests
  - java -jar target/*.war &
  - sleep 60
  - yarn e2e
  - kill $!
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_BRANCH" == "heroku" ]; then
      ./mvnw com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy -DskipTests -Pprod,heroku -Dheroku.appName=qualitoast ;
    fi
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
