version: '2'
services:
    qualitoast-app:
        image: qualitoast
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://qualitoast-postgresql:5432/QualiToast
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    qualitoast-postgresql:
        extends:
            file: postgresql.yml
            service: qualitoast-postgresql
